name: Upload Release Asset

on: push
#   release:
#     types: [published]

jobs:
  release:
    name: Release
    strategy:
        matrix:
            kind: ['linux', 'windows', 'macOS']
            include:
              - kind: linux
                os: ubuntu-latest
                target: linux-x64
                release_suffix: ''
              - kind: windows
                os: windows-latest
                target: win-x64
                release_suffix: .exe
              - kind: macOS
                os: macos-latest
                target: osx-x64
                release_suffix: ''
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x'

      - name: Build
        shell: bash
        run: |
            # Define some variables for things we need
            tag=$(git describe --tags --abbrev=0)
            release_name="App-$tag-${{ matrix.target }}"

            # Build everything
            dotnet publish ./demo_client/src/oauth-nhsd-api/oauth-nhsd-api.csproj -c Release -o "$release_name" -r "${{matrix.target}}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            name: ${{matrix.kind}}_democlient${{matrix.release_suffix}}
            files: $release_name/oauth-nhsd-api${{matrix.release_suffix}}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
